---
- name: Provision CTF VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
      - import_tasks: tasks/users.yml
      - import_tasks: tasks/challenges.yml
  handlers:
        - import_tasks: handlers/restart-ssh.yml
